<?php
#!/usr/bin/php
require "./header.phtml";

// Initialize the session
//session_start();
 
// Check if the user is logged in, if not then redirect him to login page
//if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
//    header("location: login.phtml");
//    exit;
//}

clearstatcache();

$mbfs = fopen('/var/www/html/logs/mb.logs', 'r+') or die('fopen failed');
fwrite($mbfs, "index page\n");
fclose($mbfs);

$query = "SELECT email FROM user_db.users WHERE seq=1";
$result = $db->query($query);
$emails = '';
if ($result->num_rows > 0) {
    $row = $result->fetch_assoc();
    $emails = $row['email'];
}

//#primary-nav {
//  background-color: skyblue;
//}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    ​<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="style.css">
    <style type="text/css">
        body{ font: 14px sans-serif; text-align: center; }
    </style>
</head>
<body>
    <div id="primary-nav" class="main_colour">
        <div class="container">
            <nav class="mb-4 navbar navbar-expand-lg navbar-dark bg-unique">
              <img src="img/road-bike-img.png" style="width:auto;height:auto;max-height:50px;padding-right:25px;" title="Progresso" alt="Logo of a company" />
              <a class="navbar-brand" href="index.phtml">Progresso</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-3" aria-controls="navbarSupportedContent-3" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-3">
                    <ul class="navbar-nav ml-auto nav-flex-icons">
<?php
if ($logged_in) {
echo '<li class="nav-item"><span class="navbar-brand">Welcome</span></li>
                       <li class="nav-brand dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i>'.$REMOTE_USER.'
                                </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-unique" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Account</a>
                                <a class="dropdown-item" href="#">Settings</a>
                                <a class="dropdown-item" href="logout.php">Logout</a>
                            </div>
                        </li>';
} else {
    echo '<li class="nav-item"><a href="login.phtml" class="btn btn-outline-light" style="width:150px;">Login</a></li></div>';
}

?>

                    </ul>
                </div>
            </nav>
            <!--/.Navbar -->
        </div>
    </div>

<!--
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="row">
            <div class="col-sm nav-item">
                <img src="img/road-bike-img.png"style="width:auto;height:auto;max-height:50px;" title="Progresso" alt="Logo of a company" />
            </div>
            <div class="col-sm nav-item">
                <h2>Progresso</h2>
            </div>
            <div class="col-sm my-2 my-lg-0" style='text-align:right'>
-->

<?php
if ($logged_in) {
echo "<p>Logged in... #1</p>";
//    echo "<a href='login.phtml' class='btn btn-outline-primary' style='width:150px;'>Login</a><br/>";

//    echo "<a href='register.phtml' class='btn btn-link'>New User</a>";
//    echo "<a href='login.phtml' target='_blank' rel='noopener' aria-label='Login'><svg class='navbar-nav-svg'  focusable='false'><title>Login</title></svg></a>";
//    echo "<a href='login.phtml' target='_blank' rel='noopener' aria-label='Login'><svg class='navbar-nav-svg' xmlns='img/athlete.png' focusable='false'><title>Login</title></svg></a>";

//<a class="nav-link p-2" href="https://twitter.com/getbootstrap" target="_blank" rel="noopener"
//aria-label="Twitter"><svg class="navbar-nav-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 416.32" focusable="false"><title>Twitter</title><path d="M160.83 416.32c193.2 0 298.92-160.22 298.92-298.92 0-4.51 0-9-.2-13.52A214 214 0 0 0 512 49.38a212.93 212.93 0 0 1-60.44 16.6 105.7 105.7 0 0 0 46.3-58.19 209 209 0 0 1-66.79 25.37 105.09 105.09 0 0 0-181.73 71.91 116.12 116.12 0 0 0 2.66 24c-87.28-4.3-164.73-46.3-216.56-109.82A105.48 105.48 0 0 0 68 159.6a106.27 106.27 0 0 1-47.53-13.11v1.43a105.28 105.28 0 0 0 84.21 103.06 105.67 105.67 0 0 1-47.33 1.84 105.06 105.06 0 0 0 98.14 72.94A210.72 210.72 0 0 1 25 370.84a202.17 202.17 0 0 1-25-1.43 298.85 298.85 0 0 0 160.83 46.92" fill="currentColor"></path></svg>
//</a>

//<img
} else {
    echo "
<div class='container'>
  <div class='row justify-content-center align-items-center'>
    <div class='form-group'>
      <a href='login.phtml' class='btn btn-outline-primary' style='width:150px;'>Sign up with Facebook</a>
      <br/><br/>
      <a href='login.phtml' class='btn btn-outline-primary' style='width:150px;'>Sign up with Google</a>
      <br/><br/>
      <div class='hr_separator'>or</div>
      <br/>
      <a href='login.phtml' class='btn btn-outline-primary' style='width:150px;'>Login</a>
    </div>
  </div>
</div>";
//    echo "<a href='reset-password.php' class='btn btn-outline-primary' style='width:150px;'>Reset Your Password</a>";
//    echo "<a href='logout.php' class='btn btn-outline-primary' style='width:150px;'>Sign Out</a>";
}
?>


<!--
            </div>
        </div>
    </nav>
-->
    <br/><br/>
    <div class="container-fluid">
        <p>This application will allow you to track your workout, set fitness goals, then see the results in a graph. The workouts will include walking, running, cycling, swimming, and more. Data can be manually entered, or can be automatically pulled from Strava. 
        <br/><br/>In the future, the workouts maybe include weight lifting, and will be compatible with other workout applications.
        </p>
    </div>
    <div>
        <p>|<?php echo $emails; ?>|</p>
    </div>
    <a href='info.phtml'>Info</a>
</body>
</html>

<!--
                <h1>Hi, <b><?php echo htmlspecialchars($_SESSION["username"]); ?></b>. Welcome to our site.</h1>
-->
